# Generated by Django 4.1 on 2023-02-14 04:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caught_fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_length', models.FloatField()),
                ('user_region', models.CharField(max_length=225)),
                ('image_url', models.CharField(max_length=225)),
                ('main_fish_accuracy', models.FloatField(null=True)),
                ('sub1_fish_accuracy', models.FloatField(null=True)),
                ('sub2_fish_accuracy', models.FloatField(null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('main_fish_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_caught_fish_set', to='fish.fish')),
                ('sub1_fish_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub1_caught_fish_set', to='fish.fish')),
                ('sub2_fish_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub2_caught_fish_set', to='fish.fish')),
            ],
        ),
    ]
