# Generated by Django 4.1.7 on 2023-04-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caught_fish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caught_fish',
            name='image_url',
            field=models.ImageField(null=True, upload_to='imgaes/'),
        ),
    ]
