# Generated by Django 4.2.1 on 2023-05-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_user_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user_image_url',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
