# Generated by Django 4.1 on 2023-02-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_rename_prohibition_period_fish_prohibition_period1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='prohibition_period1',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
