# Generated by Django 4.1 on 2023-02-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0003_alter_fish_prohibition_period1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='is_deleted',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
