# Generated by Django 4.1 on 2023-02-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0005_remove_fish_prohibition_period1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishimage',
            name='is_deleted',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='fishimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
