# Generated by Django 4.1 on 2023-02-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0006_alter_fishimage_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishimage',
            name='image_url',
            field=models.FileField(upload_to=''),
        ),
    ]
