# Generated by Django 4.1 on 2023-02-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0007_alter_fishimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishimage',
            name='image_url',
            field=models.CharField(max_length=225),
        ),
    ]
