# Generated by Django 4.1 on 2023-02-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0008_alter_fishimage_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testfield', models.CharField(max_length=200)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
    ]
