# Generated by Django 4.1 on 2023-02-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0009_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
