# Generated by Django 4.1.7 on 2023-03-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0008_rename_end_date2_fish_end_date_and_more'),
        ('fish', '0010_delete_test'),
    ]

    operations = [
    ]
