# Generated by Django 4.1.7 on 2023-04-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0011_merge_20230326_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='E_fish_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
