# Generated by Django 4.2.1 on 2023-05-09 16:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0013_alter_fish_e_fish_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishimage',
            name='fish_id',
        ),
        migrations.AddField(
            model_name='fishimage',
            name='fish_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fish.fish'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='E_fish_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='fishimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fishimage',
            name='image_url',
            field=models.CharField(default='', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='fishimage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fishimage',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
