# Generated by Django 4.2.1 on 2023-05-09 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0014_remove_fishimage_fish_id_fishimage_fish_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishimage',
            name='fish_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fish.fish'),
        ),
        migrations.AlterField(
            model_name='fishimage',
            name='fish_name',
            field=models.CharField(default='', max_length=50, null=True, unique=True),
        ),
    ]
